# Generated by Django 4.0.3 on 2022-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userLogin', models.CharField(max_length=255)),
                ('userFirstName', models.CharField(max_length=255)),
                ('userLastName', models.CharField(max_length=255)),
                ('userPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
