# Generated by Django 4.0.3 on 2022-03-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('equipment', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('square', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('ugs', models.CharField(max_length=200)),
                ('designConcept', models.CharField(max_length=200)),
                ('diamino', models.CharField(max_length=200)),
                ('laser3d', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=200)),
                ('samplesAreWitnesses', models.CharField(max_length=200)),
                ('executor', models.CharField(max_length=200)),
                ('laborIntensity', models.CharField(max_length=200)),
                ('dc', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('quantityA4', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Compartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=200)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviadb.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviadb.compartments')),
            ],
        ),
    ]
