# Generated by Django 4.0.3 on 2022-04-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='product',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='productName',
            field=models.CharField(default='Models', max_length=200),
        ),
        migrations.AlterField(
            model_name='compartments',
            name='drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviadb.aircraft'),
        ),
    ]
