# Generated by Django 4.0.3 on 2022-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0002_remove_aircraft_product_aircraft_productname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='compartments',
            options={'verbose_name': 'Имя детали', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='drawing',
            options={'verbose_name': 'Чертеж', 'verbose_name_plural': 'Чертежи'},
        ),
        migrations.AddField(
            model_name='aircraft',
            name='description',
            field=models.CharField(default='Description', help_text='Описание модели самолета', max_length=200),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='productName',
            field=models.CharField(default='Models', help_text='Название модели', max_length=200),
        ),
    ]
