# Generated by Django 4.0.3 on 2022-04-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0003_alter_aircraft_options_alter_compartments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='compartments',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.RenameField(
            model_name='compartments',
            old_name='drawing',
            new_name='aircraft',
        ),
        migrations.AddField(
            model_name='drawing',
            name='compartments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviadb.compartments'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='description',
            field=models.CharField(default='Description', help_text='Описание модели самолета', max_length=400),
        ),
        migrations.AlterField(
            model_name='compartments',
            name='partName',
            field=models.CharField(help_text='Название детали', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='complexity',
            field=models.CharField(help_text='Сложность оснастки', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='dc',
            field=models.CharField(help_text='DC', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='designConcept',
            field=models.CharField(help_text='Design Concept', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='diamino',
            field=models.CharField(help_text='Diamino', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='equipment',
            field=models.CharField(help_text='Оснастка', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='executor',
            field=models.CharField(help_text='Испольнитель', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='laborIntensity',
            field=models.CharField(help_text='Трудоемкость', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='laser3d',
            field=models.CharField(help_text='Laser3D', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='material',
            field=models.CharField(help_text='Материал', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='name',
            field=models.CharField(help_text='Название', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='plan',
            field=models.CharField(help_text='Чертеж', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='quantityA4',
            field=models.CharField(help_text='Количество A4', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='revision',
            field=models.CharField(help_text='Ревизия', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='samplesAreWitnesses',
            field=models.CharField(help_text='Образцы свидетели', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='square',
            field=models.CharField(help_text='Площадь', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='ugs',
            field=models.CharField(help_text='UGS', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='weight',
            field=models.CharField(help_text='Масса', max_length=200),
        ),
    ]
