# Generated by Django 4.0.3 on 2022-04-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0005_alter_drawing_compartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='compartments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviadb.compartments'),
        ),
    ]
