# Generated by Django 4.0.3 on 2022-04-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0006_alter_drawing_compartments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartments',
            old_name='aircraft',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='drawing',
            old_name='compartments',
            new_name='detail',
        ),
    ]
