# Generated by Django 4.0.3 on 2022-04-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0007_rename_aircraft_compartments_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='detail',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aviadb.compartments'),
        ),
    ]
