# Generated by Django 4.0.3 on 2022-04-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0010_remove_drawing_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aviadb.compartments'),
        ),
    ]
