# Generated by Django 4.0.3 on 2022-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0011_drawing_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
