# Generated by Django 4.0.3 on 2022-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0013_alter_drawing_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='detail',
            field=models.CharField(max_length=5),
        ),
    ]
