# Generated by Django 4.0.3 on 2022-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0015_alter_drawing_detail_alter_drawing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='dc',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='designConcept',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='laborIntensity',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='ugs',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='square',
            field=models.CharField(help_text='Общая площадь', max_length=200),
        ),
    ]
