# Generated by Django 4.0.4 on 2022-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0016_remove_drawing_complexity_remove_drawing_dc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='photo',
            field=models.CharField(default='/', help_text='Ссылка на фото', max_length=200),
        ),
    ]
