# Generated by Django 4.0.4 on 2022-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0017_aircraft_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
