# Generated by Django 4.0.4 on 2022-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0019_alter_aircraft_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='name',
            field=models.CharField(help_text='Название изделия', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='quantityA4',
            field=models.CharField(help_text='Кол-во A4', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='square',
            field=models.CharField(help_text='Общая площадь, м^2', max_length=200),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='weight',
            field=models.CharField(help_text='Масса, кг', max_length=200),
        ),
    ]
