# Generated by Django 4.0.4 on 2022-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviadb', '0020_drawing_planfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='planFile',
            field=models.FileField(default='plan.jpg', upload_to='files', verbose_name='Файл'),
        ),
    ]
